# Generated by Django 6.0.5 on 2026-05-13 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={'ordering': ['title'], 'verbose_name': 'Кофейня', 'verbose_name_plural': 'Кофейни'},
        ),
        migrations.AddField(
            model_name='cafe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/', verbose_name='Фото кофейни'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
