# Generated by Django 6.0.5 on 2026-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Списано бонусов'),
        ),
    ]
